version: "2"

services:
  site:
    container_name: vietduc01100001.github.io
    command: jekyll serve --watch --incremental
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
