backend:
  name: git-gateway
  branch: master

media_folder: "static/media"
public_folder: "/media"

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}" # used to generate filenames
    preview_path: "posts/{{slug}}"
    fields:
      - label: "Template"
        name: "template"
        widget: "hidden"
        default: "post"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: false
        hint: "Default to the slugified title"
        # If this field is left empty, the URL slug will
        # be the filename. And because filename cannot
        # be changed once created, the slug will never
        # change -> GOOD.
        # If this field is set, as long as we don't
        # change it again, we're fine -> GOOD.

      - label: "Social Image"
        name: "socialImage"
        widget: "image"

      - label: "Draft"
        name: "draft"
        widget: "hidden"
        default: false
        # No need to draft when using editorial_workflow.
        # Each post will be in a separate PR.

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Category"
        name: "category"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Tags"
        name: "tags"
        widget: "list"

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Template"
        name: "template"
        widget: "hidden"
        default: "page"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug"
        name: "slug"
        widget: "string"

      - label: "Social Image"
        name: "socialImage"
        widget: "image"

      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true

      - label: "Body"
        name: "body"
        widget: "markdown"
